# Generated by Django 4.2.7 on 2025-11-12 22:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_contact',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stage', models.CharField(choices=[('prospect', 'Prospect'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospect', max_length=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('probability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes_text', models.TextField(blank=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_deal',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted to Contact')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes_text', models.TextField(blank=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_lead',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_contact', to='crm.lead'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('task', 'Task'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'db_table': 'crm_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='crm.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='crm.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='crm.lead')),
            ],
            options={
                'db_table': 'crm_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'lead'], name='crm_note_account_219271_idx'), models.Index(fields=['account', 'contact'], name='crm_note_account_1add50_idx'), models.Index(fields=['account', 'deal'], name='crm_note_account_41389d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['account', 'status'], name='crm_lead_account_4c4b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['account', 'assigned_to'], name='crm_lead_account_051fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['account', 'email'], name='crm_lead_account_33b59b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['account', 'created_at'], name='crm_lead_account_777b34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('account', 'email')},
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['account', 'stage'], name='crm_deal_account_96736e_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['account', 'assigned_to'], name='crm_deal_account_6d90a6_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['account', 'expected_close_date'], name='crm_deal_account_c93ace_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['account', 'created_at'], name='crm_deal_account_04ad9d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', 'email'], name='crm_contact_account_313b68_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', 'company'], name='crm_contact_account_ed4f85_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', 'created_at'], name='crm_contact_account_374b82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('account', 'email')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['account', 'activity_type'], name='crm_activit_account_650146_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['account', 'due_date'], name='crm_activit_account_34a607_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['account', 'completed'], name='crm_activit_account_5a760d_idx'),
        ),
    ]
