# Generated by Django 4.2.7 on 2025-11-15 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_create_activity_note_tables'),
        ('accounts', '0002_alter_account_managers'),
        ('integrations', '0002_email_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_type', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads (Facebook & Instagram)'), ('tiktok_ads', 'TikTok Ads'), ('shopify', 'Shopify')], max_length=50)),
                ('name', models.CharField(help_text='User-friendly name for this plugin connection', max_length=200)),
                ('category', models.CharField(choices=[('advertising', 'Advertising Platform'), ('ecommerce', 'E-commerce Platform')], max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=1000)),
                ('client_secret', models.CharField(blank=True, max_length=1000)),
                ('access_token', models.CharField(blank=True, max_length=2000)),
                ('refresh_token', models.CharField(blank=True, max_length=2000)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict, help_text='Platform-specific settings like ad account ID, store domain, etc.')),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for receiving events from platform', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook verification', max_length=255)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('pending', 'Pending Authorization')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.IntegerField(default=3600, help_text='Sync frequency in seconds (default: 1 hour)')),
                ('last_error', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('total_syncs', models.IntegerField(default=0)),
                ('failed_syncs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='accounts.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('account', 'plugin_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PluginSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(help_text='Type of sync operation (e.g., campaigns, orders, customers)', max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.plugin')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('google_ads.campaign.created', 'Google Ads - Campaign Created'), ('google_ads.campaign.updated', 'Google Ads - Campaign Updated'), ('google_ads.ad.created', 'Google Ads - Ad Created'), ('google_ads.conversion', 'Google Ads - Conversion'), ('meta_ads.campaign.created', 'Meta Ads - Campaign Created'), ('meta_ads.campaign.updated', 'Meta Ads - Campaign Updated'), ('meta_ads.ad.created', 'Meta Ads - Ad Created'), ('meta_ads.lead', 'Meta Ads - Lead Generated'), ('tiktok_ads.campaign.created', 'TikTok Ads - Campaign Created'), ('tiktok_ads.campaign.updated', 'TikTok Ads - Campaign Updated'), ('tiktok_ads.ad.created', 'TikTok Ads - Ad Created'), ('shopify.order.created', 'Shopify - Order Created'), ('shopify.order.updated', 'Shopify - Order Updated'), ('shopify.customer.created', 'Shopify - Customer Created'), ('shopify.product.created', 'Shopify - Product Created')], max_length=100)),
                ('event_id', models.CharField(help_text="Platform's event/webhook ID", max_length=255)),
                ('payload', models.JSONField(help_text='Raw webhook payload from platform')),
                ('processed_data', models.JSONField(default=dict, help_text='Processed/normalized data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_events', to='crm.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_events', to='crm.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_events', to='crm.lead')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.plugin')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plugin', 'event_type'], name='integration_plugin__c65de0_idx'), models.Index(fields=['status', 'created_at'], name='integration_status_c936b2_idx')],
            },
        ),
    ]
