# Generated by Django 4.2.7 on 2025-11-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_remove_webhook_models'),
        ('integrations', '0004_campaignabtest_campaigngoal_dripcampaign_and_more'),
    ]

    operations = [
    ]
