# Generated by Django 4.2.7 on 2025-11-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='insight_type',
            field=models.CharField(choices=[('lead_score', 'Lead Scoring'), ('deal_prediction', 'Deal Prediction'), ('sentiment', 'Sentiment Analysis'), ('suggestion', 'Smart Suggestion'), ('summary', 'Summary'), ('agent_query', 'Agent Query'), ('agent_lead', 'Agent Lead Action'), ('agent_deal', 'Agent Deal Action'), ('agent_report', 'Agent Report')], max_length=50),
        ),
    ]
