# Generated by Django 4.2.7 on 2025-11-09 19:38

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customobject',
            managers=[
                ('objects', accounts.managers.AccountManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customobjectrecord',
            managers=[
                ('objects', accounts.managers.AccountManager()),
            ],
        ),
    ]
