# Generated by Django 4.2.7 on 2025-11-13 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_managers"),
        ("custom_objects", "0002_alter_customobject_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customfield",
            name="default_value",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customfield",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("deal", "Deal"),
                    ("contact", "Contact"),
                    ("lead", "Lead"),
                    ("custom", "Custom Object"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="custom_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="custom_objects.customobject",
            ),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Long Text"),
                    ("number", "Number"),
                    ("currency", "Currency"),
                    ("date", "Date"),
                    ("boolean", "Yes/No"),
                    ("select", "Dropdown"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                ],
                max_length=20,
            ),
        ),
    ]
